### ISSUE TITLE
[Indexer API] for mainnet is not working 

### ISSUE THREAD

**Issue by tharunhack** [aptos-labs/aptos-indexer-processors#223]
## Description
While using 
const client = new IndexerClient(
            "https://indexer.mainnet.aptoslabs.com/v1/graphql"
          );
const txnDetails = await client.getAccountTransactionsData(
            "0x62818ab1a3567b03bdb19078e42b774fbdab279a2bf5dfae886d29461feb1fcd"
          );
          console.log("txnDetails: ", txnDetails);
         
this is my error 
{
    "errors": [
        {
            "message": "Connection template evaluation failed: 'Object' has no attritubte 'operation_name'.",
            "extensions": {
                "path": "$",
                "code": "template-resolution-failed"
            }
        }
    ]
}

**Comment by banool** [comment]
Hi, this was a known issue with our infra that we have now resolved. Please reopen the issue if you see this is still an issue.
