### ISSUE TITLE
How can the value of indexer_api_key be obtained?

### ISSUE THREAD

**Issue by nangongamo** [aptos-labs/aptos-indexer-processors#28]
Where can the value of **indexer_api_key** in the `config.yaml` configuration file be obtained from? thanks！

**Comment by larry-aptos** [comment]
We are set to exit alpha testing 05/26. If you’re interested, please join
our Discord group for more  details.

**Comment by larry-aptos** [comment]
To be clear, we will release a dev portal with self-service indexer api key
generation very soon.

**Comment by nangongamo** [comment]
> To be clear, we will release a dev portal with self-service indexer api key generation very soon.

Awesome, I'm looking forward to it.

**Comment by larry-aptos** [comment]
Just FYI, the portal is available now: [developers.aptoslabs.com](https://t.co/CSZJ59huNX)
