### ISSUE TITLE
[Transaction Stream Service] Focus contract address confusingly ignores wrapped calls

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-indexer-processors#339]
cc @banool @CapCap @crbl69

## Description

The focus contract address alpha feature is presumably intended to simplify client filtering behavior: only events corresponding to a particular Move package are allowed through the top-level worker process

However, the underlying implementation appears to filter based on the public entry function rather than by the event address. E.g. if a project composes on top of another and invokes the underlying package via a wrapped function call, then the wrapping package's events (which are also the wrapped package's events) get removed

Instead, it is suggested that filtration rely on the address of emitted event types, or alternatively, the `focus_contract_addresses` be renamed to something like `entry_function_address` with an additional `event_type_address`

## Repro

```
server_config:
  transaction_filter:
    focus_contract_addresses:
      - $ECONIA_ADDRESS
```

**Comment by alnoki** [comment]
> which transactions are needed and only them will be streamed.

@larry-aptos 

Will this filtering function filter on event address or on entry function? If the latter, it doesn't solve the original problem

**Comment by larry-aptos** [comment]
@grao1991 who is working on this; we can share the design doc for review when it's ready.

**Comment by grao1991** [comment]
@alnoki we can do whatever filtering logic that makes sense to developer, as long as the logic is not too computational heavy. @rtso is going to define the interface.

**Comment by alnoki** [comment]
> we can share the design doc for review when it's ready.

@larry-aptos  @grao1991 @rtso please do, thank you!!
