### ISSUE TITLE
[Indexer API] events directory

### ISSUE THREAD

**Issue by MYMEILE** [aptos-labs/aptos-indexer-processors#603]
## Repro

When I customize the indexer, I don't know what events means. Where can I find something similar to the events directory?

**Comment by larry-aptos** [comment]
events are emitted when transaction is executed. you can start from here https://aptos.dev/en/network/blockchain/events

to visualize the events, you can use node API like this https://mainnet.aptoslabs.com/v1/transactions/by_version/1898174711 to check which events are emitted.
